### ISSUE TITLE
Add project blog

### ISSUE THREAD

**Issue by chauhankaranraj** [aicoe-aiops/openshift-anomaly-detection#8]
As a data scientist I want to add a blog describing the project so that it is easier to understand the motivation of the notebooks, the approaches we have taken, what are the next steps, and how to contribute to the project.

**Comment by MichaelClifford** [comment]
@chauhankaranraj will this blog also replace the current README?

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj will this blog also replace the current README?

Good question, I hadn't really thought about that :thinking:

I was thinking maybe the README can have a very brief description about this effort and the instructions for running on MOC JH, and the blog can have the finer details of the methods explored in the notebooks. Would we be better off putting all of it in one big README? WDYT?

**Comment by MichaelClifford** [comment]
Yeah, that makes sense. I was just looking at this repo which still has the template README so I was thinking, either the blog and the readme are the same or the readme should come first. 

OR really the readme is a subset of the blog, but should be published here before a blog is promoted.

**Comment by chauhankaranraj** [comment]
> OR really the readme is a subset of the blog, but should be published here before a blog is promoted.

This sounds like a good idea :)
